### ISSUE TITLE
Are you planning to add the login as well?

### ISSUE THREAD

**Issue by MihailButnaru** [janos-gonye/django-rest-jwt-registration#1]
Are you planning to add the login as well? after confirming the email to login successfully?

**Comment by MihailButnaru** [comment]
I think this will be great, tested registration and is working as expected. Thank you

**Comment by janos-gonye** [comment]
I have abandoned this project for some time but planning to continue and make some additions/changes.

I'm planning the following at least:
- Refactor code and take advantage of type hinting.
- Add unit and integration tests. The project is worth nothing without those.
- Allow one to change one's password if forgotten. Currently, only a newly generated password is supported.

> Are you planning to add the login as well? after confirming the email to login successfully?

I'm not planning to add the login since this package is fully compatible with the stable, tested, and well-documented [Django Rest Framework Simple JWT package](https://github.com/jazzband/djangorestframework-simplejwt). So, if you need login and logout, that package is just perfect for you.

> I think this will be great, tested registration and is working as expected. Thank you

Thank you :)
